services:
  pdf-document-layout-analysis-toc:
    extends:
      file: docker-compose.yml
      service: pdf-document-layout-analysis-toc
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]