services:
  pdf-document-layout-analysis-toc:
    extends:
      file: docker-compose.yml
      service: pdf-document-layout-analysis-toc
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    networks:
      - pdf-table-of-contents-network

  pdf-table-of-contents-extraction:
    extends:
      file: docker-compose.yml
      service: pdf-table-of-contents-extraction
    networks:
      - pdf-table-of-contents-network

networks:
  pdf-table-of-contents-network:
    driver: bridge
